ENT.Base 			= "obj_vj_wzs_zombiegas_miniboss"
ENT.Type 			= "ai"
ENT.PrintName 		= "Spawner"
ENT.Author 			= "Bean"
ENT.Contact 		= "http://steamcommunity.com/groups/vrejgaming"
ENT.Purpose 		= "Spawns things for you."
ENT.Instructions 	= "Do you really need instructions for this?"
ENT.Category		= "Warkins Zombie Survival"