ENT.Base 			= "npc_vj_wzs_ghoul"
ENT.Type 			= "ai"
ENT.PrintName 		= "Alpha Ghoul"
ENT.Author 			= "Warkin"
ENT.Contact 		= "http://steamcommunity.com/groups/vrejgaming"
ENT.Purpose 		= "Spawn it and fight with it!"
ENT.Instructions 	= "Click on the spawnicon to spawn it."
ENT.Category		= "NPC"